run-clang-tidy -header-filter='.*' -checks='-*,modernize-avoid-bind' -fix ./build/
run-clang-tidy -header-filter='.*' -checks='-*,modernize-deprecated-headers' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-loop-convert' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-make-shared' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-make-unique' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-pass-by-value' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-raw-string-literal' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-redundant-void-arg' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-replace-auto-ptr' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-shrink-to-fit' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-auto' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-bool-literals' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-default-member-init' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-emplace' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-equals-default' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-equals-delete' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-nullptr' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-override' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-transparent-functors' -fix
run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-using' -fix